image: java:8

pipelines:
  branches:
    master:
    - step:
        caches:
        - gradle
        name: Publish
        script:
        - bash ./gradlew publish -PDEVEO_PASSWORD=$DEVEO_PASSWORD -PDEVEO_USERNAME=$DEVEO_USERNAME
